### PR TITLE
Rarity

### PR DESCRIPTION
**Pull request by ghost**
color rarity

### CODE REVIEW

**Comment by ghost** [comment]
please

**Comment by ghost** [comment]
option or easy access to this edit

**Comment by CleverNucleus** [comment]
Any specific reason for this?

**Comment by ghost** [comment]
yeah, for a modpack, the rarity color isn't the same and also different than most games. It also could be amazing and include more personnalisation. I don't think a color edit is hard to make ?

**Comment by ghost** [comment]
A color setting could be also amazing

**Comment by CleverNucleus** [comment]
I will implement color configuration in next release - thanks for the suggestion!

**Comment by ghost** [comment]
thank you so much !

**Pull request closed without merging**
