### PR TITLE
zh_cn locale remade

### PR DESCRIPTION
**Pull request by ChromaPIE**
Reason why:
- Overall poor quality
- Nonsense contents not present in en_us, such as 血 (blood) in Dragon Stone
- Missing contents, like Regret in Orb of Regret. They simply translated it to 遗物之球 (relic sphere)
- Taking advice from search engine results
- Smuggling goofy expressions, like translating Reset to level 0 to 还俗 (secularizing)
- Trying to explain the gameplay in the config tooltips, though they're supposed to pertain in a wiki, description or item tooltips.

Still it's okay if it's not guaranteed to be merged immediately, and it's fine if you decided to keep that one and close the pull request just because their wholesome words.

### CODE REVIEW

**Comment by CleverNucleus** [comment]
Hi there,
I appreciate the work - I obviously don't speak Chinese so am unable to tell what is a good translation and what is a bad one; hence, I tend to just accept and include any provided translation.

For the same reason I'll accept this merge.
Thanks!

Edit: I'll look to include this in the next release; however, no timeframe for when that will be.

**Comment by CleverNucleus** [comment]
Hi @ChromaPIE,
Just wanted to run this by you:

```json
{
  "text.autoconfig.relicex.option.mobDropBlacklist": "Mob Drop Blacklist",
  "text.autoconfig.relicex.option.mobDropBlacklist.@Tooltip": "Entity types in this list will not drop relics/health potions.",
}
```

Would you be willing to translate this? I'm implementing a new config feature and just wondered for completion's sake.

No worries if not though!
Thanks.

**Comment by ChromaPIE** [comment]
@CleverNucleus thank god i didnt forget to check the inbox, least not for months long. the two lines will be `掉落战利品怪物黑名单` and `所设定类型的实体不会掉落遗物及生命药水。`. Just copy&paste and it'll be all fine or wait for like 10 hours for me to get time to make another pull request. Thanks for the @ anyway! mod devs wouldn't let new releases wait for the little locale follow-up normally lol

**Comment by CleverNucleus** [comment]
No problem, thought I'd ask anyway haha.
Thanks for the quick reply!

**Pull request merged**
