### PR TITLE
Translation: I have translated RelicEx into Chinese for 100%

### PR DESCRIPTION
**Pull request by MoneySoup008**
There is the json:
`{
	"text.autoconfig.relicex.title": "RelicEx Config Options",
	"text.autoconfig.relicex.option.chestsHaveLoot": "宝箱生成圣物物品",
	"text.autoconfig.relicex.option.chestsHaveLoot.@Tooltip": "若启用, 将在宝箱中生成圣物道具",
	"text.autoconfig.relicex.option.chestsHaveRelicChance": "宝箱生成遗物的概率",
	"text.autoconfig.relicex.option.chestsHaveRelicChance.@Tooltip": "将会有多少概率在宝箱中生成圣物战利品",
	"text.autoconfig.relicex.option.chestsHaveLesserOrbChance": "宝箱生成小遗物之球的概率",
	"text.autoconfig.relicex.option.chestsHaveLesserOrbChance.@Tooltip": "将会有多少概率在宝箱中生成小遗物之球",
	"text.autoconfig.relicex.option.chestsHaveGreaterOrbChance": "宝箱生成大遗物之球的概率",
	"text.autoconfig.relicex.option.chestsHaveGreaterOrbChance.@Tooltip": "将会有多少概率在宝箱中生成大遗物之球",
	"text.autoconfig.relicex.option.chestsHaveTomeChance": "宝箱生成巨著的概率",
	"text.autoconfig.relicex.option.chestsHaveTomeChance.@Tooltip": "将会有多少概率在宝箱中生成巨著",
	"text.autoconfig.relicex.option.dragonDropsStone": "龙血石",
	"text.autoconfig.relicex.option.dragonDropsStone.@Tooltip": "若启用, 末影龙会在死亡时掉落龙血石",
	"text.autoconfig.relicex.option.mobsDropLootChance": "怪物掉落概率",
	"text.autoconfig.relicex.option.mobsDropLootChance.@Tooltip": "怪物掉落圣物战利品的概率",
	"text.autoconfig.relicex.option.dropsOnlyFromPlayerKills": "仅玩家击杀",
	"text.autoconfig.relicex.option.dropsOnlyFromPlayerKills.@Tooltip": "如果启用, 怪物则仅会在玩家击杀所造成的死亡之前提下掉落圣物战利品",
	"text.autoconfig.relicex.option.mobDropIsRelicChance": "模组专属的强化怪物(血条超越原版怪物, 但外貌与原版怪物无异)的掉落概率",
	"text.autoconfig.relicex.option.mobDropIsRelicChance.@Tooltip": "将会有多少概率让强化怪物掉落圣物战利品",
	"text.autoconfig.relicex.option.mobDropIsPotionChance": "生命恢复药掉率",
	"text.autoconfig.relicex.option.mobDropIsPotionChance.@Tooltip": "将会有多少概率在击杀怪物后掉落生命恢复药(生命回复药并不是药剂, 而是一个瞬间拾取瞬间使用的道具, 有专属音效)",
	"text.autoconfig.relicex.option.mobDropIsLesserOrbChance": "小遗物之球掉落概率(仅模组专属强化怪掉落)",
	"text.autoconfig.relicex.option.mobDropIsLesserOrbChance.@Tooltip": "强化怪物掉落小遗物之球的概率",
	"text.autoconfig.relicex.option.mobDropIsGreaterOrbChance": "大遗物之球掉落概率(同小遗物之球)",
	"text.autoconfig.relicex.option.mobDropIsGreaterOrbChance.@Tooltip": "强化怪物掉落大遗物之球的概率",
	"text.autoconfig.relicex.option.mobDropIsTomeChance": "巨著掉率(同大小球)",
	"text.autoconfig.relicex.option.mobDropIsTomeChance.@Tooltip": "强化怪物掉落巨著的概率",
	"item.relicex.small_health_potion": "小型生命回复药",
    "item.relicex.medium_health_potion": "中型生命回复药",
    "item.relicex.large_health_potion": "大型生命回复药",
    "item.relicex.tome": "巨著",
    "item.relicex.dragon_stone": "龙血石",
    "item.relicex.lesser_orb_of_regret": "小遗物之球",
    "item.relicex.greater_orb_of_regret": "大遗物之球",
    "item.relicex.amulet_relic": "护身符",
    "item.relicex.ring_relic": "戒指",
    "item.relicex.head_relic": "头盔",
    "item.relicex.chest_relic": "胸甲",
    "item.relicex.relic_shard": "圣物碎片",
    "tooltip.relicex.worn": "穿戴时:",
    "tooltip.relicex.tome": "这本巨著蕴含着神秘力量(level:+1)",
    "tooltip.relicex.dragon_stone": "重置等级",
    "tooltip.relicex.greater_orb_of_regret": "重置所有等级点数",
    "tooltip.relicex.lesser_orb_of_regret": "重置1点等级点数",
    "message.relicex.dragon_stone": "准备好还俗了吗?(重复右键使用确认还俗!)",
    "rareness.relicex.common": "普通",
    "rareness.relicex.uncommon": "非同寻常",
    "rareness.relicex.rare": "稀有",
    "rareness.relicex.epic": "史诗",
    "rareness.relicex.mythical": "神秘",
    "rareness.relicex.legendary": "传说",
    "rareness.relicex.immortal": "不朽",
    "sound.relicex.level_refund": "重置等级音效",
    "sound.relicex.potion_use": "生命回复药音效{
	"text.autoconfig.relicex.title": "RelicEx Config Options",
	"text.autoconfig.relicex.option.chestsHaveLoot": "宝箱生成圣物物品",
	"text.autoconfig.relicex.option.chestsHaveLoot.@Tooltip": "若启用, 将在宝箱中生成圣物道具",
	"text.autoconfig.relicex.option.chestsHaveRelicChance": "宝箱生成遗物的概率",
	"text.autoconfig.relicex.option.chestsHaveRelicChance.@Tooltip": "将会有多少概率在宝箱中生成圣物战利品",
	"text.autoconfig.relicex.option.chestsHaveLesserOrbChance": "宝箱生成小遗物之球的概率",
	"text.autoconfig.relicex.option.chestsHaveLesserOrbChance.@Tooltip": "将会有多少概率在宝箱中生成小遗物之球",
	"text.autoconfig.relicex.option.chestsHaveGreaterOrbChance": "宝箱生成大遗物之球的概率",
	"text.autoconfig.relicex.option.chestsHaveGreaterOrbChance.@Tooltip": "将会有多少概率在宝箱中生成大遗物之球",
	"text.autoconfig.relicex.option.chestsHaveTomeChance": "宝箱生成巨著的概率",
	"text.autoconfig.relicex.option.chestsHaveTomeChance.@Tooltip": "将会有多少概率在宝箱中生成巨著",
	"text.autoconfig.relicex.option.dragonDropsStone": "龙血石",
	"text.autoconfig.relicex.option.dragonDropsStone.@Tooltip": "若启用, 末影龙会在死亡时掉落龙血石",
	"text.autoconfig.relicex.option.mobsDropLootChance": "怪物掉落概率",
	"text.autoconfig.relicex.option.mobsDropLootChance.@Tooltip": "怪物掉落圣物战利品的概率",
	"text.autoconfig.relicex.option.dropsOnlyFromPlayerKills": "仅玩家击杀",
	"text.autoconfig.relicex.option.dropsOnlyFromPlayerKills.@Tooltip": "如果启用, 怪物则仅会在玩家击杀所造成的死亡之前提下掉落圣物战利品",
	"text.autoconfig.relicex.option.mobDropIsRelicChance": "模组专属的强化怪物(血条超越原版怪物, 但外貌与原版怪物无异)的掉落概率",
	"text.autoconfig.relicex.option.mobDropIsRelicChance.@Tooltip": "将会有多少概率让强化怪物掉落圣物战利品",
	"text.autoconfig.relicex.option.mobDropIsPotionChance": "生命恢复药掉率",
	"text.autoconfig.relicex.option.mobDropIsPotionChance.@Tooltip": "将会有多少概率在击杀怪物后掉落生命恢复药(生命回复药并不是药剂, 而是一个瞬间拾取瞬间使用的道具, 有专属音效)",
	"text.autoconfig.relicex.option.mobDropIsLesserOrbChance": "小遗物之球掉落概率(仅模组专属强化怪掉落)",
	"text.autoconfig.relicex.option.mobDropIsLesserOrbChance.@Tooltip": "强化怪物掉落小遗物之球的概率",
	"text.autoconfig.relicex.option.mobDropIsGreaterOrbChance": "大遗物之球掉落概率(同小遗物之球)",
	"text.autoconfig.relicex.option.mobDropIsGreaterOrbChance.@Tooltip": "强化怪物掉落大遗物之球的概率",
	"text.autoconfig.relicex.option.mobDropIsTomeChance": "巨著掉率(同大小球)",
	"text.autoconfig.relicex.option.mobDropIsTomeChance.@Tooltip": "强化怪物掉落巨著的概率",
	"item.relicex.small_health_potion": "小型生命回复药",
    "item.relicex.medium_health_potion": "中型生命回复药",
    "item.relicex.large_health_potion": "大型生命回复药",
    "item.relicex.tome": "巨著",
    "item.relicex.dragon_stone": "龙血石",
    "item.relicex.lesser_orb_of_regret": "小遗物之球",
    "item.relicex.greater_orb_of_regret": "大遗物之球",
    "item.relicex.amulet_relic": "护身符",
    "item.relicex.ring_relic": "戒指",
    "item.relicex.head_relic": "头盔",
    "item.relicex.chest_relic": "胸甲",
    "item.relicex.relic_shard": "圣物碎片",
    "tooltip.relicex.worn": "穿戴时:",
    "tooltip.relicex.tome": "这本巨著蕴含着神秘力量(level:+1)",
    "tooltip.relicex.dragon_stone": "重置等级",
    "tooltip.relicex.greater_orb_of_regret": "重置所有等级点数",
    "tooltip.relicex.lesser_orb_of_regret": "重置1点等级点数",
    "message.relicex.dragon_stone": "准备好还俗了吗?(重复右键使用确认还俗!)",
    "rareness.relicex.common": "普通",
    "rareness.relicex.uncommon": "非同寻常",
    "rareness.relicex.rare": "稀有",
    "rareness.relicex.epic": "史诗",
    "rareness.relicex.mythical": "神秘",
    "rareness.relicex.legendary": "传说",
    "rareness.relicex.immortal": "不朽",
    "sound.relicex.level_refund": "重置等级音效",
    "sound.relicex.potion_use": "生命回复药音效"
}`

### CODE REVIEW

**Comment by MoneySoup008** [comment]
If you are interested, you can add this localization json to your next update.
It's 100% suported.

**Comment by MoneySoup008** [comment]
Sorry for the chaos of text board, I have been edit it well, but somehow it shows the weird way.

**Comment by CleverNucleus** [comment]
Hi there,
I appreciate this, and will add the Chinese localisation you have provided. However, I like to keep my build and versioning consistent across my mods and their dependencies, so I tend to only update the build all at once. For this reason I am not merging this, but know that I am still going to include your contribution.
Thanks.

**Comment by MoneySoup008** [comment]
Anytime, :D it's a pleasure to translate my favorite Mod.
Thank you to create this mod.

**Pull request closed without merging**
